services:
  - type: web
    name: orange-laravel
    env: docker
    plan: free
    region: singapore # Change as needed
    dockerfilePath: Dockerfile
    healthCheckPath: /up
    envVars:
      - key: APP_ENV
        value: production
      - key: DB_URL
        sync: false
      - key: FILESYSTEM_DISK
        value: public
      - key: SESSION_DRIVER
        value: cookie
      - key: CACHE_STORE
        value: file
